# Generated by Django 3.0.3 on 2020-02-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='body',
            field=models.TextField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['pub_date', 'user'], name='journal_jou_pub_dat_4669f7_idx'),
        ),
    ]
